### ISSUE TITLE
Set up Redux, Redux Persist, and the store

### ISSUE THREAD

**Issue by Zino0031** [Zino0031/Noteapp#1]
**Task title**
Set up Redux, Redux Persist, and the store

**Task description**
Configure Redux and integrate Redux Persist to persist the Redux store across sessions.

**Subtasks**
- [x] Install Redux and React-Redux
- [x] Create Redux Store
- [x] Integrate Redux in the App
- [x] Install Redux Persist
- [x] Configure Redux Persist
- [x] Wrap App with PersistGate
