### ISSUE TITLE
Implement a feature to show connected users.

### ISSUE THREAD

**Issue by Zino0031** [Zino0031/Noteapp#12]
**Task title**
Implement a feature to show connected users.

**Task description**
Develop functionality that allows users to view a list of connected users in the application.

**Subtasks**
- [x] Design the UI to display the list of connected users.
- [x] Implement logic to retrieve and update the list of connected users.
- [x] Connect the logic with the application's state using Redux
- [x] Update the Firebase Firestore and Realtime Database with information related to connected users.
- [x] Display users numbers 
- [x] Implement real-time updates to reflect changes in the list of connected users.
