### ISSUE TITLE
Create an end session details page.

### ISSUE THREAD

**Issue by Zino0031** [Zino0031/Noteapp#13]
**Task title**
Create an end session details page.

**Task description**
Develop a page that provides details and information when a session comes to an end.

**Subtasks**
- [ ] Design the UI for the end session details page.
- [ ] Implement logic to fetch and display relevant details about the completed session.
- [ ] Include information and show them in table 
- [ ] Design and implement visual elements to summarize the session.
- [ ] Implement logic to handle and fetch from database
