### ISSUE TITLE
Set up Firebase in the project

### ISSUE THREAD

**Issue by Zino0031** [Zino0031/Noteapp#3]
**Task title**
Set up Firebase in the project

**Task description**
Configure Firebase for your application, including authentication, database, and hosting.

**Subtasks**
- [x] Create a Firebase project on the Firebase Console.
- [x] Configure Firebase  Firestore.
- [x] Integrate Firebase SDK into the project.
- [x] Initialize Firebase in your application.
- [x] Connect your application to Firebase Database or Firestore.
