### ISSUE TITLE
Create a Attend Page with options for join and Host

### ISSUE THREAD

**Issue by Zino0031** [Zino0031/Noteapp#6]
**Task title**
Create a Attend Page with options for join and Host

**Task description**
Design and implement a Attend page that provides clear options for users to Host and Join.

**Subtasks**
- [x] Design the layout and user interface for the attend page.
- [x] Add a Join Button
- [x] Add a Host Button
- [x] Ensure responsive design for various screen sizes.
- [x] Add appropriate styling to enhance user experience.
