### ISSUE TITLE
Implement the logic for creating a new session, integrate Redux, and store data in Firebase.

### ISSUE THREAD

**Issue by Zino0031** [Zino0031/Noteapp#7]
**Task title**
Implement the logic for creating a new session, integrate Redux, and store data in Firebase.

**Task description**
Create a feature that allows users to initiate and create a new session, while ensuring the data is managed using Redux and stored in Firebase.

**Subtasks**
- [x] Design the user interface for creating a new session.
- [x] Implement logic for user input and validation during session creation.
- [x] Implement logic fir user to preview Data before creating session
- [x] Integrate Redux to manage state related to new sessions.
- [x] Create Redux actions and reducers for handling new session data.
- [x] Connect the new session UI components with Redux.
- [x] Implement logic for storing new session data in Firebase.
- [x] Create Session successfully Created Page with Data to join
