### ISSUE TITLE
Create a host function, design the host UI

### ISSUE THREAD

**Issue by Zino0031** [Zino0031/Noteapp#8]
**Task title**
Create a host function, design the host UI

**Task description**
Implement a feature that allows users to become hosts, design the corresponding user interface, and generate a unique session pin and code for the host's session.

**Subtasks**
- [x] Design the host user interface with relevant controls and information.
- [x] Implement logic for users to become hosts within the application.
- [x] Generate a unique session pin for the host's session.
- [x] Generate a unique session code for the host's session.
- [x] Host With code and pin
- [x] Host directly after create a session
- [x] Host user session using droplist
- [x] Display the generated session pin to the host user.
- [x] Connect the host Data with the application's state using Redux.
- [x] Update the backend or Firebase Firestore
